/*PÁGINA DO EMPRÉSTIMO*/

SELECT ID_EXEMPLAR, ISBN
FROM TB_EXEMPLAR 
WHERE STATUS = 'Disponível'
ORDER BY RAND() LIMIT 1;       
        
INSERT INTO tb_emprestimo(usuario, exemplar, data_emprestimo, bibliotecaria)
VALUES((SELECT ID_USUARIO FROM TB_USUARIO WHERE CPF = :CPF), (SELECT ID_EXEMPLAR FROM TB_EXEMPLAR WHERE ISBN = :ISBN), NOW(), (SELECT CHAVE_ACESSO FROM TB_BIBLIOTECARIA WHERE CHAVE_ACESSO = :CHAVE_ACESSO);

UPDATE tb_exemplar
SET STATUS_EXEMPLAR = 'Emprestado'
WHERE ID_EXEMPLAR = :id_exemplar;
