/*EMPRÉSTIMOS EM ANDAMENTO*/

SELECT U.NOME_USUARIO, U.CPF, U.TIPO, U.TURMA, L.TITULO_LIVRO, E.DATA_EMPRESTIMO, EX.ISBN 
FROM tb_usuario U 
INNER JOIN TB_EMPRESTIMO E
ON U.id_usuario = E.USUARIO
INNER JOIN tb_exemplar EX
ON EX.id_exemplar = E.exemplar
INNER JOIN TB_LIVRO L
ON L.ISBN = EX.ISBN;