/*PÁGINA DO LIVRO*/
SELECT L.TITULO_LIVRO, L.EDICAO, L.ANO_EDICAO, L.PAGINAS, L.CAPA, A.NOME_AUTOR, C.CATEGORIA 
FROM TB_LIVRO AS L
INNER JOIN TB_AUTOR AS A
ON L.AUTOR = A.ID_AUTOR
INNER JOIN TB_CATEGORIA C
ON C.ID_CATEGORIA = L.CATEGORIA;

SELECT ISBN, COUNT(*) AS 'QUANTIDADE NO ACERVO' 
FROM TB_EXEMPLAR
GROUP BY ISBN;